### ISSUE TITLE
FUTCHAMPIONS

### ISSUE THREAD

**Issue by crysthal6** [opera-gaming/gxmods#235]
para los aficionados del futbol

for football `fans****`
```[tasklist]
### Tasks
- [ ] https://github.com/opera-gaming/gxmods/issues/136
```

```[tasklist]
### Tasks
- [ ] https://github.com/opera-gaming/gxmods/issues/136
```

```[tasklist]
### Tasks
- [ ] https://github.com/opera-gaming/gxmods/issues/136
```

**Comment by crysthal6** [comment]
![Opera Instantánea_2023-09-05_171556_www google com](https://github.com/opera-gaming/gxmods/assets/171632888/4df72946-8c7e-44ff-92b0-0f21f054d915)

**Comment by crysthal6** [comment]
b
