### ISSUE TITLE
Gojo

### ISSUE THREAD

**Issue by Ronilton14** [opera-gaming/gxmods#253]
Uploading Vídeo do WhatsApp de 2024-07-24 à(s) 18.41.59_8ae3e892.mp4…

```[tasklist]
### Tasks
- [ ] https://github.com/opera-gaming/gxmods/issues/251
- [ ] https://github.com/opera-gaming/gxmods/issues/252
- [ ] https://github.com/opera-gaming/gxmods/issues/247
```

**Comment by Ronilton14** [comment]
Uploading Vídeo do WhatsApp de 2024-07-24 à(s) 18.41.59_8ae3e892.mp4…
